import Vue from 'vue'
import VueClipboard from 'vue-clipboard2'
import VToasted from 'vue-toasted'
import colors from 'vuetify/es5/util/colors'
import {
  Vuetify,
  VApp,
  VCard,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VGrid,
  VToolbar,
  VForm,
  VTextField,
  VSelect,
  VCheckbox,
  // VTimePicker,
  VDatePicker,
  VDataTable,
  VMenu,
  VDivider,
  // VAlert,
  // VSubheader,
  VTabs,
  // VAvatar,
  // VBreadcrumbs,
  // VStepper,
  // VPagination,
  // VTooltip,
  VDialog,
  // VDataIterator,
  // VSwitch,
  // VChip,
  VSnackbar,
  VProgressCircular,
  VSpeedDial
} from 'vuetify'

Vue.use(Vuetify, {
  theme: {
    primary: colors.red.darken2,
    secondary: colors.red.lighten4,
    accent: colors.blue.lighten3,
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  },
  components: {
    VApp,
    VCard,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VGrid,
    VToolbar,
    VForm,
    VTextField,
    VSelect,
    VCheckbox,
    // VTimePicker,
    VDatePicker,
    VDataTable,
    VMenu,
    VDivider,
    // VAlert,
    // VSubheader,
    VTabs,
    // VAvatar,
    // VBreadcrumbs,
    // VStepper,
    // VPagination,
    // VTooltip,
    VDialog,
    // VDataIterator,
    // VSwitch,
    // VChip,
    VSnackbar,
    VProgressCircular,
    VSpeedDial,
    VueClipboard,
    VToasted
  }
})
